//! Apache Kafka 4.3.1's `KafkaConfig` key roster: every broker key the
//! released broker defines, with its `ConfigDef` type, its default, whether an
//! alter may set it dynamically, and the value check it applies.
//!
//! Three surfaces read it.
//!
//! - **The alter paths.** `DynamicBrokerConfig.validateConfigs` refuses every
//!   `KafkaConfig` key that is not dynamic, and `DynamicConfig.Broker.validate`
//!   parses and range-checks every key that is. A name the roster does not hold
//!   is not a `KafkaConfig` key, and Kafka stores it unchecked.
//! - **`DescribeConfigs`.** `KafkaConfig.configType` types a key by this roster,
//!   and `KafkaConfig.maybeSensitive` withholds the value of a `PASSWORD` key
//!   and of a name Kafka does not define. A named broker lists every
//!   non-internal key, at its default unless the process was started with a
//!   value.
//! - **`APPEND` and `SUBTRACT`**, which Kafka allows on a `LIST` key alone.
//!
//! # Where the rows come from
//!
//! The rows are `AbstractKafkaConfig.CONFIG_DEF` of the Apache Kafka 4.3.1
//! sources, which is the merge of the `CONFIG_DEF` of `RemoteLogManagerConfig`,
//! `ServerConfigs`, `KRaftConfigs`, `MetadataLogConfig`, `SocketServerConfigs`,
//! `ReplicationConfigs`, `GroupCoordinatorConfig`, `CleanerConfig`,
//! `LogConfig.SERVER_CONFIG_DEF`, `ShareGroupConfig`, `ShareCoordinatorConfig`,
//! `TransactionLogConfig`, `TransactionStateManagerConfig`, `QuorumConfig`,
//! `MetricConfigs`, `QuotaConfig`, `BrokerSecurityConfigs`,
//! `DelegationTokenManagerConfigs` and `AddPartitionsToTxnConfig`. They were
//! read out of the loaded `ConfigDef` objects (`ConfigKey.type`,
//! `defaultValue` through `ConfigDef.convertToString`, `internalConfig`), not
//! transcribed. 360 keys, 20 of them internal.
//!
//! The dynamic column is `DynamicBrokerConfig.ALL_DYNAMIC_CONFIGS` (99 of the
//! 360 keys), and the per-broker column is its `PER_BROKER_CONFIGS`:
//! `SslConfigs.RECONFIGURABLE_CONFIGS`, `DynamicListenerConfig`, and
//! `cordoned.log.dirs`, less the three cluster-level listener keys. The three
//! `QuotaConfig.brokerQuotaConfigs()` keys are dynamic too, but are not
//! `KafkaConfig` keys, so [`crate::throttle`] owns them.
//!
//! The check column carries only what an alter of a *dynamic* key can trip,
//! which is `Range.atLeast`, `ValidString.in` and `ValidList`. The topic
//! synonyms carry their topic key's own check instead (see
//! [`super::broker_dynamic`]), so a key with a stricter validator than the one
//! here is checked by that validator first.
//!
//! Kafka trunk's broker keys are not here. Under
//! `unstable.api.versions.enable`, [`super::broker_dynamic`] adds the broker
//! synonyms of trunk's topic keys on top of this roster.

use super::{
    parse::{
        check_one_of, check_range, check_valid_list, java_double, java_trim, parse_bool,
        parse_double, parse_int, parse_long, parse_short,
    },
    registry::{
        ConfigKey, ConfigScope,
        ConfigType::{
            self, Boolean as Bool, Class, Double, Int, List, Long, Password, Short, String as Str,
        },
        ValueCheck,
    },
};

/// Whether an alter may set a key, and where.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Dynamic {
    /// Not in `ALL_DYNAMIC_CONFIGS`: the process reads it at startup, and an
    /// alter is refused with `Cannot update these configs dynamically`.
    ReadOnly,
    /// A cluster-wide default, which a named broker may also override.
    Cluster,
    /// `PER_BROKER_CONFIGS`: valid on a named broker alone.
    PerBroker,
}

use Dynamic::{Cluster, PerBroker, ReadOnly};

/// The value check `DynamicConfig.Broker.validate` applies to a dynamic key,
/// after the type parse.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Check {
    /// The type parse is the whole check.
    Free,
    /// `Range.atLeast(n)` on an `INT`, `SHORT` or `LONG`.
    AtLeast(i64),
    /// `ValidString.in(..)`.
    OneOf(&'static [&'static str]),
    /// `ValidList.anyNonDuplicateValues(false, false)`: a list that may be
    /// neither empty nor repeat an element. Every other `LIST` key allows the
    /// empty list.
    NonEmptyList,
}

use Check::{AtLeast, Free, NonEmptyList, OneOf};

/// One key of `AbstractKafkaConfig.CONFIG_DEF`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct KafkaBrokerConfig {
    pub(crate) name: &'static str,
    /// `ConfigKey.type`.
    pub(crate) config_type: ConfigType,
    /// `ConfigDef.convertToString` of `ConfigKey.defaultValue`; `None` is
    /// Kafka's `null`, and a key with no default at all.
    pub(crate) default: Option<&'static str>,
    pub(crate) dynamic: Dynamic,
    /// `ConfigKey.internalConfig`, which `KafkaConfig.nonInternalValues`
    /// leaves out of a named broker's `DescribeConfigs`.
    pub(crate) internal: bool,
    check: Check,
}

const fn k(
    name: &'static str,
    config_type: ConfigType,
    default: Option<&'static str>,
    dynamic: Dynamic,
    check: Check,
) -> KafkaBrokerConfig {
    KafkaBrokerConfig {
        name,
        config_type,
        default,
        dynamic,
        internal: false,
        check,
    }
}

/// [`k`] for a key Kafka defines with `defineInternal`.
const fn ki(
    name: &'static str,
    config_type: ConfigType,
    default: Option<&'static str>,
    dynamic: Dynamic,
    check: Check,
) -> KafkaBrokerConfig {
    KafkaBrokerConfig {
        internal: true,
        ..k(name, config_type, default, dynamic, check)
    }
}

/// Every `KafkaConfig` key of Apache Kafka 4.3.1, sorted by name.
pub(crate) const KAFKA_BROKER_CONFIGS: &[KafkaBrokerConfig] = &[
    k(
        "add.partitions.to.txn.retry.backoff.max.ms",
        Int,
        Some("100"),
        ReadOnly,
        Free,
    ),
    k(
        "add.partitions.to.txn.retry.backoff.ms",
        Int,
        Some("20"),
        ReadOnly,
        Free,
    ),
    k("advertised.listeners", List, None, ReadOnly, Free),
    k(
        "alter.config.policy.class.name",
        Class,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "alter.log.dirs.replication.quota.window.num",
        Int,
        Some("11"),
        ReadOnly,
        Free,
    ),
    k(
        "alter.log.dirs.replication.quota.window.size.seconds",
        Int,
        Some("1"),
        ReadOnly,
        Free,
    ),
    k("authorizer.class.name", Str, Some(""), ReadOnly, Free),
    k(
        "auto.create.topics.enable",
        Bool,
        Some("true"),
        ReadOnly,
        Free,
    ),
    k(
        "auto.leader.rebalance.enable",
        Bool,
        Some("true"),
        ReadOnly,
        Free,
    ),
    k("background.threads", Int, Some("10"), Cluster, AtLeast(1)),
    k(
        "broker.heartbeat.interval.ms",
        Int,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    k("broker.id", Int, Some("-1"), ReadOnly, Free),
    k("broker.rack", Str, None, ReadOnly, Free),
    k(
        "broker.session.timeout.ms",
        Int,
        Some("9000"),
        ReadOnly,
        Free,
    ),
    k("client.quota.callback.class", Class, None, ReadOnly, Free),
    k("compression.gzip.level", Int, Some("-1"), Cluster, Free),
    k("compression.lz4.level", Int, Some("9"), Cluster, Free),
    k("compression.type", Str, Some("producer"), Cluster, Free),
    k("compression.zstd.level", Int, Some("3"), Cluster, Free),
    k("config.providers", List, Some(""), Cluster, Free),
    k(
        "connection.failed.authentication.delay.ms",
        Int,
        Some("100"),
        ReadOnly,
        Free,
    ),
    k(
        "connections.max.idle.ms",
        Long,
        Some("600000"),
        ReadOnly,
        Free,
    ),
    k("connections.max.reauth.ms", Long, Some("0"), ReadOnly, Free),
    k(
        "controlled.shutdown.enable",
        Bool,
        Some("true"),
        ReadOnly,
        Free,
    ),
    k("controller.listener.names", List, None, ReadOnly, Free),
    ki(
        "controller.performance.always.log.threshold.ms",
        Long,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    ki(
        "controller.performance.sample.period.ms",
        Long,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.append.linger.ms",
        Int,
        Some("25"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.auto.join.enable",
        Bool,
        Some("false"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.bootstrap.servers",
        List,
        Some(""),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.election.backoff.max.ms",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.election.timeout.ms",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.fetch.max.bytes",
        Int,
        Some("1048576"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.fetch.snapshot.max.bytes",
        Int,
        Some("1048576"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.fetch.timeout.ms",
        Int,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.request.timeout.ms",
        Int,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quorum.retry.backoff.ms",
        Int,
        Some("20"),
        ReadOnly,
        Free,
    ),
    k("controller.quorum.voters", List, Some(""), ReadOnly, Free),
    k(
        "controller.quota.window.num",
        Int,
        Some("11"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.quota.window.size.seconds",
        Int,
        Some("1"),
        ReadOnly,
        Free,
    ),
    k(
        "controller.socket.timeout.ms",
        Int,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k("cordoned.log.dirs", List, Some(""), PerBroker, Free),
    k(
        "create.topic.policy.class.name",
        Class,
        None,
        ReadOnly,
        Free,
    ),
    k("default.replication.factor", Int, Some("1"), ReadOnly, Free),
    k(
        "delegation.token.expiry.check.interval.ms",
        Long,
        Some("3600000"),
        ReadOnly,
        Free,
    ),
    k(
        "delegation.token.expiry.time.ms",
        Long,
        Some("86400000"),
        ReadOnly,
        Free,
    ),
    k(
        "delegation.token.max.lifetime.ms",
        Long,
        Some("604800000"),
        ReadOnly,
        Free,
    ),
    k(
        "delegation.token.secret.key",
        Password,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "delete.records.purgatory.purge.interval.requests",
        Int,
        Some("1"),
        ReadOnly,
        Free,
    ),
    k("delete.topic.enable", Bool, Some("true"), ReadOnly, Free),
    k("early.start.listeners", List, None, ReadOnly, Free),
    k("fetch.max.bytes", Int, Some("57671680"), ReadOnly, Free),
    k(
        "fetch.purgatory.purge.interval.requests",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k(
        "follower.fetch.last.tiered.offset.enable",
        Bool,
        Some("false"),
        Cluster,
        Free,
    ),
    k(
        "group.consumer.assignment.interval.ms",
        Int,
        Some("1000"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "group.consumer.assignors",
        List,
        Some("uniform,range"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.heartbeat.interval.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.max.assignment.interval.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.max.heartbeat.interval.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.max.session.timeout.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.max.size",
        Int,
        Some("2147483647"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.migration.policy",
        Str,
        Some("bidirectional"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.min.assignment.interval.ms",
        Int,
        Some("0"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.min.heartbeat.interval.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.min.session.timeout.ms",
        Int,
        Some("45000"),
        ReadOnly,
        Free,
    ),
    ki(
        "group.consumer.regex.refresh.interval.ms",
        Int,
        Some("600000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.consumer.session.timeout.ms",
        Int,
        Some("45000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.coordinator.append.linger.ms",
        Int,
        Some("-1"),
        ReadOnly,
        Free,
    ),
    k(
        "group.coordinator.background.threads",
        Int,
        Some("2"),
        ReadOnly,
        Free,
    ),
    k(
        "group.coordinator.cached.buffer.max.bytes",
        Int,
        Some("1048588"),
        Cluster,
        AtLeast(524_288),
    ),
    k(
        "group.coordinator.rebalance.protocols",
        List,
        Some("classic,consumer,streams"),
        ReadOnly,
        Free,
    ),
    k("group.coordinator.threads", Int, Some("4"), ReadOnly, Free),
    k(
        "group.initial.rebalance.delay.ms",
        Int,
        Some("3000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.max.session.timeout.ms",
        Int,
        Some("1800000"),
        ReadOnly,
        Free,
    ),
    k("group.max.size", Int, Some("2147483647"), ReadOnly, Free),
    k(
        "group.min.session.timeout.ms",
        Int,
        Some("6000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.assignment.interval.ms",
        Int,
        Some("1000"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "group.share.assignors",
        List,
        Some("simple"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.delivery.count.limit",
        Int,
        Some("5"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.heartbeat.interval.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    ki(
        "group.share.initialize.retry.interval.ms",
        Int,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.assignment.interval.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.delivery.count.limit",
        Int,
        Some("10"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.heartbeat.interval.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.partition.max.record.locks",
        Int,
        Some("4000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.record.lock.duration.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.session.timeout.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.max.share.sessions",
        Int,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    k("group.share.max.size", Int, Some("200"), ReadOnly, Free),
    k(
        "group.share.min.assignment.interval.ms",
        Int,
        Some("0"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.min.delivery.count.limit",
        Int,
        Some("2"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.min.heartbeat.interval.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.min.partition.max.record.locks",
        Int,
        Some("100"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.min.record.lock.duration.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.min.session.timeout.ms",
        Int,
        Some("45000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.partition.max.record.locks",
        Int,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    ki(
        "group.share.persister.class.name",
        Str,
        Some("org.apache.kafka.server.share.persister.DefaultStatePersister"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.record.lock.duration.ms",
        Int,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.share.session.timeout.ms",
        Int,
        Some("45000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.assignment.interval.ms",
        Int,
        Some("1000"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "group.streams.heartbeat.interval.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.initial.rebalance.delay.ms",
        Int,
        Some("3000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.max.assignment.interval.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.max.heartbeat.interval.ms",
        Int,
        Some("15000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.max.session.timeout.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.max.size",
        Int,
        Some("2147483647"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.max.standby.replicas",
        Int,
        Some("2"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.min.assignment.interval.ms",
        Int,
        Some("0"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.min.heartbeat.interval.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.min.session.timeout.ms",
        Int,
        Some("45000"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.num.standby.replicas",
        Int,
        Some("0"),
        ReadOnly,
        Free,
    ),
    k(
        "group.streams.session.timeout.ms",
        Int,
        Some("45000"),
        ReadOnly,
        Free,
    ),
    k(
        "initial.broker.registration.timeout.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k("inter.broker.listener.name", Str, None, ReadOnly, Free),
    ki(
        "internal.metadata.delete.delay.millis",
        Long,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    ki(
        "internal.metadata.log.segment.bytes",
        Int,
        None,
        ReadOnly,
        Free,
    ),
    ki(
        "internal.metadata.max.batch.size.in.bytes",
        Int,
        Some("8388608"),
        ReadOnly,
        Free,
    ),
    k(
        "kafka.metrics.polling.interval.secs",
        Int,
        Some("10"),
        ReadOnly,
        Free,
    ),
    k("kafka.metrics.reporters", List, Some(""), ReadOnly, Free),
    k(
        "leader.imbalance.check.interval.seconds",
        Long,
        Some("300"),
        ReadOnly,
        Free,
    ),
    k(
        "listener.security.protocol.map",
        Str,
        Some("SASL_SSL:SASL_SSL,PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT"),
        PerBroker,
        Free,
    ),
    k(
        "listeners",
        List,
        Some("PLAINTEXT://:9092"),
        PerBroker,
        NonEmptyList,
    ),
    k(
        "log.cleaner.backoff.ms",
        Long,
        Some("15000"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "log.cleaner.dedupe.buffer.size",
        Long,
        Some("134217728"),
        Cluster,
        Free,
    ),
    k(
        "log.cleaner.delete.retention.ms",
        Long,
        Some("86400000"),
        Cluster,
        AtLeast(0),
    ),
    k("log.cleaner.enable", Bool, Some("true"), ReadOnly, Free),
    k(
        "log.cleaner.io.buffer.load.factor",
        Double,
        Some("0.9"),
        Cluster,
        Free,
    ),
    k(
        "log.cleaner.io.buffer.size",
        Int,
        Some("524288"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "log.cleaner.io.max.bytes.per.second",
        Double,
        Some("1.7976931348623157E308"),
        Cluster,
        Free,
    ),
    k(
        "log.cleaner.max.compaction.lag.ms",
        Long,
        Some("9223372036854775807"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "log.cleaner.min.cleanable.ratio",
        Double,
        Some("0.5"),
        Cluster,
        Free,
    ),
    k(
        "log.cleaner.min.compaction.lag.ms",
        Long,
        Some("0"),
        Cluster,
        AtLeast(0),
    ),
    k("log.cleaner.threads", Int, Some("1"), Cluster, AtLeast(0)),
    k("log.cleanup.policy", List, Some("delete"), Cluster, Free),
    k("log.dir", List, Some("/tmp/kafka-logs"), ReadOnly, Free),
    k(
        "log.dir.failure.timeout.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k("log.dirs", List, None, ReadOnly, Free),
    k(
        "log.flush.interval.messages",
        Long,
        Some("9223372036854775807"),
        Cluster,
        AtLeast(1),
    ),
    k("log.flush.interval.ms", Long, None, Cluster, Free),
    k(
        "log.flush.offset.checkpoint.interval.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "log.flush.scheduler.interval.ms",
        Long,
        Some("9223372036854775807"),
        ReadOnly,
        Free,
    ),
    k(
        "log.flush.start.offset.checkpoint.interval.ms",
        Int,
        Some("60000"),
        ReadOnly,
        Free,
    ),
    k(
        "log.index.interval.bytes",
        Int,
        Some("4096"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "log.index.size.max.bytes",
        Int,
        Some("10485760"),
        Cluster,
        AtLeast(4),
    ),
    ki(
        "log.initial.task.delay.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k(
        "log.local.retention.bytes",
        Long,
        Some("-2"),
        Cluster,
        AtLeast(-2),
    ),
    k(
        "log.local.retention.ms",
        Long,
        Some("-2"),
        Cluster,
        AtLeast(-2),
    ),
    k(
        "log.message.timestamp.after.max.ms",
        Long,
        Some("3600000"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "log.message.timestamp.before.max.ms",
        Long,
        Some("9223372036854775807"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "log.message.timestamp.type",
        Str,
        Some("CreateTime"),
        Cluster,
        Free,
    ),
    k("log.preallocate", Bool, Some("false"), Cluster, Free),
    k("log.retention.bytes", Long, Some("-1"), Cluster, Free),
    k(
        "log.retention.check.interval.ms",
        Long,
        Some("300000"),
        ReadOnly,
        Free,
    ),
    k("log.retention.hours", Int, Some("168"), ReadOnly, Free),
    k("log.retention.minutes", Int, None, ReadOnly, Free),
    k("log.retention.ms", Long, None, Cluster, Free),
    k("log.roll.hours", Int, Some("168"), ReadOnly, Free),
    k("log.roll.jitter.hours", Int, Some("0"), ReadOnly, Free),
    k("log.roll.jitter.ms", Long, None, Cluster, Free),
    k("log.roll.ms", Long, None, Cluster, Free),
    k(
        "log.segment.bytes",
        Int,
        Some("1073741824"),
        Cluster,
        AtLeast(1_048_576),
    ),
    k(
        "log.segment.delete.delay.ms",
        Long,
        Some("60000"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "max.connection.creation.rate",
        Int,
        Some("2147483647"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "max.connections",
        Int,
        Some("2147483647"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "max.connections.per.ip",
        Int,
        Some("2147483647"),
        Cluster,
        AtLeast(0),
    ),
    k(
        "max.connections.per.ip.overrides",
        Str,
        Some(""),
        Cluster,
        Free,
    ),
    k(
        "max.incremental.fetch.session.cache.slots",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k(
        "max.request.partition.size.limit",
        Int,
        Some("2000"),
        ReadOnly,
        Free,
    ),
    k(
        "message.max.bytes",
        Int,
        Some("1048588"),
        Cluster,
        AtLeast(0),
    ),
    k("metadata.log.dir", Str, None, ReadOnly, Free),
    k(
        "metadata.log.max.record.bytes.between.snapshots",
        Long,
        Some("20971520"),
        ReadOnly,
        Free,
    ),
    k(
        "metadata.log.max.snapshot.interval.ms",
        Long,
        Some("3600000"),
        ReadOnly,
        Free,
    ),
    k(
        "metadata.log.segment.bytes",
        Int,
        Some("1073741824"),
        ReadOnly,
        Free,
    ),
    k(
        "metadata.log.segment.ms",
        Long,
        Some("604800000"),
        ReadOnly,
        Free,
    ),
    k(
        "metadata.max.idle.interval.ms",
        Int,
        Some("500"),
        ReadOnly,
        Free,
    ),
    k(
        "metadata.max.retention.bytes",
        Long,
        Some("104857600"),
        ReadOnly,
        Free,
    ),
    k(
        "metadata.max.retention.ms",
        Long,
        Some("604800000"),
        ReadOnly,
        Free,
    ),
    k(
        "metric.reporters",
        List,
        Some("org.apache.kafka.common.metrics.JmxReporter"),
        Cluster,
        Free,
    ),
    k("metrics.num.samples", Int, Some("2"), ReadOnly, Free),
    k("metrics.recording.level", Str, Some("INFO"), ReadOnly, Free),
    k(
        "metrics.sample.window.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k("min.insync.replicas", Int, Some("1"), Cluster, AtLeast(1)),
    k("node.id", Int, None, ReadOnly, Free),
    k("num.io.threads", Int, Some("8"), Cluster, AtLeast(1)),
    k("num.network.threads", Int, Some("3"), Cluster, AtLeast(1)),
    k("num.partitions", Int, Some("1"), ReadOnly, Free),
    k(
        "num.recovery.threads.per.data.dir",
        Int,
        Some("2"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "num.replica.alter.log.dirs.threads",
        Int,
        None,
        ReadOnly,
        Free,
    ),
    k("num.replica.fetchers", Int, Some("1"), Cluster, AtLeast(1)),
    k(
        "offset.metadata.max.bytes",
        Int,
        Some("4096"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.commit.timeout.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.load.buffer.size",
        Int,
        Some("5242880"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.retention.check.interval.ms",
        Long,
        Some("600000"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.retention.minutes",
        Int,
        Some("10080"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.topic.compression.codec",
        Int,
        Some("0"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.topic.num.partitions",
        Int,
        Some("50"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.topic.replication.factor",
        Short,
        Some("3"),
        ReadOnly,
        Free,
    ),
    k(
        "offsets.topic.segment.bytes",
        Int,
        Some("104857600"),
        ReadOnly,
        Free,
    ),
    k(
        "principal.builder.class",
        Class,
        Some("org.apache.kafka.common.security.authenticator.DefaultKafkaPrincipalBuilder"),
        PerBroker,
        Free,
    ),
    k("process.roles", List, None, ReadOnly, Free),
    ki(
        "producer.id.expiration.check.interval.ms",
        Int,
        Some("600000"),
        ReadOnly,
        Free,
    ),
    k(
        "producer.id.expiration.ms",
        Int,
        Some("86400000"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "producer.purgatory.purge.interval.requests",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k("queued.max.request.bytes", Long, Some("-1"), ReadOnly, Free),
    k("queued.max.requests", Int, Some("500"), ReadOnly, Free),
    k("quota.window.num", Int, Some("11"), ReadOnly, Free),
    k("quota.window.size.seconds", Int, Some("1"), ReadOnly, Free),
    k(
        "remote.fetch.max.wait.ms",
        Int,
        Some("500"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.list.offsets.request.timeout.ms",
        Long,
        Some("30000"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.index.file.cache.total.size.bytes",
        Long,
        Some("1073741824"),
        Cluster,
        AtLeast(1),
    ),
    ki(
        "remote.log.index.file.cache.ttl.ms",
        Long,
        Some("900000"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.manager.copier.thread.pool.size",
        Int,
        Some("10"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.manager.copy.max.bytes.per.second",
        Long,
        Some("9223372036854775807"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.manager.copy.quota.window.num",
        Int,
        Some("11"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.manager.copy.quota.window.size.seconds",
        Int,
        Some("1"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.manager.expiration.thread.pool.size",
        Int,
        Some("10"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.manager.fetch.max.bytes.per.second",
        Long,
        Some("9223372036854775807"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.manager.fetch.quota.window.num",
        Int,
        Some("11"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.manager.fetch.quota.window.size.seconds",
        Int,
        Some("1"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.manager.follower.thread.pool.size",
        Int,
        Some("2"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.manager.task.interval.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    ki(
        "remote.log.manager.task.retry.backoff.max.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    ki(
        "remote.log.manager.task.retry.backoff.ms",
        Long,
        Some("500"),
        ReadOnly,
        Free,
    ),
    ki(
        "remote.log.manager.task.retry.jitter",
        Double,
        Some("0.2"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.manager.thread.pool.size",
        Int,
        Some("2"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.metadata.custom.metadata.max.bytes",
        Int,
        Some("128"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.metadata.manager.class.name",
        Str,
        Some(
            "org.apache.kafka.server.log.remote.metadata.storage.TopicBasedRemoteLogMetadataManager",
        ),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.metadata.manager.class.path",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.metadata.manager.impl.prefix",
        Str,
        Some("rlmm.config."),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.metadata.manager.listener.name",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.reader.max.pending.tasks",
        Int,
        Some("100"),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.reader.threads",
        Int,
        Some("10"),
        Cluster,
        AtLeast(1),
    ),
    k(
        "remote.log.storage.manager.class.name",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.storage.manager.class.path",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.storage.manager.impl.prefix",
        Str,
        Some("rsm.config."),
        ReadOnly,
        Free,
    ),
    k(
        "remote.log.storage.system.enable",
        Bool,
        Some("false"),
        ReadOnly,
        Free,
    ),
    k(
        "replica.fetch.backoff.ms",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k(
        "replica.fetch.max.bytes",
        Int,
        Some("1048576"),
        ReadOnly,
        Free,
    ),
    k("replica.fetch.min.bytes", Int, Some("1"), ReadOnly, Free),
    k(
        "replica.fetch.response.max.bytes",
        Int,
        Some("10485760"),
        ReadOnly,
        Free,
    ),
    k(
        "replica.fetch.wait.max.ms",
        Int,
        Some("500"),
        ReadOnly,
        Free,
    ),
    k(
        "replica.high.watermark.checkpoint.interval.ms",
        Long,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "replica.lag.time.max.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k("replica.selector.class", Str, None, ReadOnly, Free),
    k(
        "replica.socket.receive.buffer.bytes",
        Int,
        Some("65536"),
        ReadOnly,
        Free,
    ),
    k(
        "replica.socket.timeout.ms",
        Int,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k(
        "replication.quota.window.num",
        Int,
        Some("11"),
        ReadOnly,
        Free,
    ),
    k(
        "replication.quota.window.size.seconds",
        Int,
        Some("1"),
        ReadOnly,
        Free,
    ),
    k("request.timeout.ms", Int, Some("30000"), ReadOnly, Free),
    k(
        "sasl.client.callback.handler.class",
        Class,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.enabled.mechanisms",
        List,
        Some("GSSAPI"),
        PerBroker,
        Free,
    ),
    k("sasl.jaas.config", Password, None, PerBroker, Free),
    k(
        "sasl.kerberos.kinit.cmd",
        Str,
        Some("/usr/bin/kinit"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.kerberos.min.time.before.relogin",
        Long,
        Some("60000"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.kerberos.principal.to.local.rules",
        List,
        Some("DEFAULT"),
        PerBroker,
        Free,
    ),
    k("sasl.kerberos.service.name", Str, None, PerBroker, Free),
    k(
        "sasl.kerberos.ticket.renew.jitter",
        Double,
        Some("0.05"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.kerberos.ticket.renew.window.factor",
        Double,
        Some("0.8"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.login.callback.handler.class",
        Class,
        None,
        ReadOnly,
        Free,
    ),
    k("sasl.login.class", Class, None, ReadOnly, Free),
    k("sasl.login.connect.timeout.ms", Int, None, ReadOnly, Free),
    k("sasl.login.read.timeout.ms", Int, None, ReadOnly, Free),
    k(
        "sasl.login.refresh.buffer.seconds",
        Short,
        Some("300"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.login.refresh.min.period.seconds",
        Short,
        Some("60"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.login.refresh.window.factor",
        Double,
        Some("0.8"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.login.refresh.window.jitter",
        Double,
        Some("0.05"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.login.retry.backoff.max.ms",
        Long,
        Some("10000"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.login.retry.backoff.ms",
        Long,
        Some("100"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.mechanism.controller.protocol",
        Str,
        Some("GSSAPI"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.mechanism.inter.broker.protocol",
        Str,
        Some("GSSAPI"),
        PerBroker,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.algorithm",
        Str,
        Some("RS256"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.claim.aud",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.claim.exp.seconds",
        Int,
        Some("300"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.claim.iss",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.claim.jti.include",
        Bool,
        Some("false"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.claim.nbf.seconds",
        Int,
        Some("60"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.claim.sub",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k("sasl.oauthbearer.assertion.file", Str, None, ReadOnly, Free),
    k(
        "sasl.oauthbearer.assertion.private.key.file",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.private.key.passphrase",
        Password,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.assertion.template.file",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.client.credentials.client.id",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.client.credentials.client.secret",
        Password,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.clock.skew.seconds",
        Int,
        Some("30"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.expected.audience",
        List,
        Some(""),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.expected.issuer",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.jwks.endpoint.refresh.ms",
        Long,
        Some("3600000"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms",
        Long,
        Some("10000"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.jwks.endpoint.retry.backoff.ms",
        Long,
        Some("100"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.jwks.endpoint.url",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.jwt.retriever.class",
        Class,
        Some("org.apache.kafka.common.security.oauthbearer.DefaultJwtRetriever"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.jwt.validator.class",
        Class,
        Some("org.apache.kafka.common.security.oauthbearer.DefaultJwtValidator"),
        ReadOnly,
        Free,
    ),
    k("sasl.oauthbearer.scope", Str, None, ReadOnly, Free),
    k(
        "sasl.oauthbearer.scope.claim.name",
        Str,
        Some("scope"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.sub.claim.name",
        Str,
        Some("sub"),
        ReadOnly,
        Free,
    ),
    k(
        "sasl.oauthbearer.token.endpoint.url",
        Str,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.server.callback.handler.class",
        Class,
        None,
        ReadOnly,
        Free,
    ),
    k(
        "sasl.server.max.receive.size",
        Int,
        Some("524288"),
        ReadOnly,
        Free,
    ),
    k(
        "security.inter.broker.protocol",
        Str,
        Some("PLAINTEXT"),
        ReadOnly,
        Free,
    ),
    k("security.providers", Str, None, ReadOnly, Free),
    ki(
        "server.max.startup.time.ms",
        Long,
        Some("9223372036854775807"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.append.linger.ms",
        Int,
        Some("-1"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.cached.buffer.max.bytes",
        Int,
        Some("1048588"),
        Cluster,
        AtLeast(524_288),
    ),
    ki(
        "share.coordinator.cold.partition.snapshot.interval.ms",
        Int,
        Some("300000"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.load.buffer.size",
        Int,
        Some("5242880"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.snapshot.update.records.per.snapshot",
        Int,
        Some("500"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.state.topic.compression.codec",
        Int,
        Some("0"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.state.topic.min.isr",
        Short,
        Some("2"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.state.topic.num.partitions",
        Int,
        Some("50"),
        ReadOnly,
        Free,
    ),
    ki(
        "share.coordinator.state.topic.prune.interval.ms",
        Int,
        Some("300000"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.state.topic.replication.factor",
        Short,
        Some("3"),
        ReadOnly,
        Free,
    ),
    k(
        "share.coordinator.state.topic.segment.bytes",
        Int,
        Some("104857600"),
        ReadOnly,
        Free,
    ),
    k("share.coordinator.threads", Int, Some("1"), ReadOnly, Free),
    k(
        "share.coordinator.write.timeout.ms",
        Int,
        Some("5000"),
        ReadOnly,
        Free,
    ),
    k(
        "share.fetch.purgatory.purge.interval.requests",
        Int,
        Some("1000"),
        ReadOnly,
        Free,
    ),
    k(
        "socket.connection.setup.timeout.max.ms",
        Long,
        Some("30000"),
        ReadOnly,
        Free,
    ),
    k(
        "socket.connection.setup.timeout.ms",
        Long,
        Some("10000"),
        ReadOnly,
        Free,
    ),
    k(
        "socket.listen.backlog.size",
        Int,
        Some("50"),
        ReadOnly,
        Free,
    ),
    k(
        "socket.receive.buffer.bytes",
        Int,
        Some("102400"),
        ReadOnly,
        Free,
    ),
    k(
        "socket.request.max.bytes",
        Int,
        Some("104857600"),
        ReadOnly,
        Free,
    ),
    k(
        "socket.send.buffer.bytes",
        Int,
        Some("102400"),
        ReadOnly,
        Free,
    ),
    k("ssl.allow.dn.changes", Bool, Some("false"), ReadOnly, Free),
    k("ssl.allow.san.changes", Bool, Some("false"), ReadOnly, Free),
    k("ssl.cipher.suites", List, Some(""), PerBroker, Free),
    k(
        "ssl.client.auth",
        Str,
        Some("none"),
        PerBroker,
        OneOf(&["required", "requested", "none"]),
    ),
    k(
        "ssl.enabled.protocols",
        List,
        Some("TLSv1.2,TLSv1.3"),
        PerBroker,
        Free,
    ),
    k(
        "ssl.endpoint.identification.algorithm",
        Str,
        Some("https"),
        PerBroker,
        Free,
    ),
    k("ssl.engine.factory.class", Class, None, PerBroker, Free),
    k("ssl.key.password", Password, None, PerBroker, Free),
    k(
        "ssl.keymanager.algorithm",
        Str,
        Some("SunX509"),
        PerBroker,
        Free,
    ),
    k(
        "ssl.keystore.certificate.chain",
        Password,
        None,
        PerBroker,
        Free,
    ),
    k("ssl.keystore.key", Password, None, PerBroker, Free),
    k("ssl.keystore.location", Str, None, PerBroker, Free),
    k("ssl.keystore.password", Password, None, PerBroker, Free),
    k("ssl.keystore.type", Str, Some("JKS"), PerBroker, Free),
    k(
        "ssl.principal.mapping.rules",
        Str,
        Some("DEFAULT"),
        ReadOnly,
        Free,
    ),
    k("ssl.protocol", Str, Some("TLSv1.3"), PerBroker, Free),
    k("ssl.provider", Str, None, PerBroker, Free),
    k(
        "ssl.secure.random.implementation",
        Str,
        None,
        PerBroker,
        Free,
    ),
    k(
        "ssl.trustmanager.algorithm",
        Str,
        Some("PKIX"),
        PerBroker,
        Free,
    ),
    k(
        "ssl.truststore.certificates",
        Password,
        None,
        PerBroker,
        Free,
    ),
    k("ssl.truststore.location", Str, None, PerBroker, Free),
    k("ssl.truststore.password", Password, None, PerBroker, Free),
    k("ssl.truststore.type", Str, Some("JKS"), PerBroker, Free),
    k("telemetry.max.bytes", Int, Some("1048576"), ReadOnly, Free),
    k(
        "transaction.abort.timed.out.transaction.cleanup.interval.ms",
        Int,
        Some("10000"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.max.timeout.ms",
        Int,
        Some("900000"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.partition.verification.enable",
        Bool,
        Some("true"),
        Cluster,
        Free,
    ),
    k(
        "transaction.remove.expired.transaction.cleanup.interval.ms",
        Int,
        Some("3600000"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.state.log.load.buffer.size",
        Int,
        Some("5242880"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.state.log.min.isr",
        Int,
        Some("2"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.state.log.num.partitions",
        Int,
        Some("50"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.state.log.replication.factor",
        Short,
        Some("3"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.state.log.segment.bytes",
        Int,
        Some("104857600"),
        ReadOnly,
        Free,
    ),
    k(
        "transaction.two.phase.commit.enable",
        Bool,
        Some("false"),
        ReadOnly,
        Free,
    ),
    k(
        "transactional.id.expiration.ms",
        Int,
        Some("604800000"),
        ReadOnly,
        Free,
    ),
    k(
        "unclean.leader.election.enable",
        Bool,
        Some("false"),
        Cluster,
        Free,
    ),
    ki(
        "unclean.leader.election.interval.ms",
        Long,
        Some("300000"),
        ReadOnly,
        Free,
    ),
    ki(
        "unstable.api.versions.enable",
        Bool,
        Some("false"),
        ReadOnly,
        Free,
    ),
    ki(
        "unstable.feature.versions.enable",
        Bool,
        Some("false"),
        ReadOnly,
        Free,
    ),
];

/// The roster row for `name`, when Kafka 4.3.1 defines it as a `KafkaConfig`
/// key.
pub(crate) fn lookup(name: &str) -> Option<&'static KafkaBrokerConfig> {
    KAFKA_BROKER_CONFIGS
        .binary_search_by(|row| row.name.cmp(name))
        .ok()
        .map(|index| &KAFKA_BROKER_CONFIGS[index])
}

/// Kafka's `LISTENER_MECHANISM_CONFIGS`: the keys a listener overrides under a
/// SASL mechanism prefix, as `listener.name.<listener>.<mechanism>.<key>`.
const LISTENER_MECHANISM_CONFIGS: &[&str] = &[
    "sasl.jaas.config",
    "sasl.login.callback.handler.class",
    "sasl.login.class",
    "sasl.server.callback.handler.class",
    "connections.max.reauth.ms",
];

/// The part of a `listener.name.<listener>.<rest>` override that follows the
/// listener name, which is Kafka's `LISTENER_CONFIG_REGEX` group.
pub(crate) fn listener_override_base(name: &str) -> Option<&str> {
    let rest = name.strip_prefix("listener.name.")?;
    let (_, base) = rest.split_once('.')?;
    Some(base)
}

/// The roster row that types `name`, as `KafkaConfig.configType` resolves it:
/// the key itself, else the key a `listener.name.<listener>.` override
/// overrides. A mechanism override such as `plain.sasl.jaas.config` resolves
/// to the mechanism-independent key it ends in.
pub(crate) fn resolve(name: &str) -> Option<&'static KafkaBrokerConfig> {
    lookup(name).or_else(|| {
        let rest = listener_override_base(name)?;
        let base = LISTENER_MECHANISM_CONFIGS
            .iter()
            .find(|mechanism| rest.ends_with(**mechanism))
            .copied()
            .unwrap_or(rest);
        lookup(base)
    })
}

impl KafkaBrokerConfig {
    /// The registry-shaped row `DescribeConfigs` shapes an entry from. The
    /// roster carries no documentation string, so the row has none.
    pub(crate) const fn row(&self) -> ConfigKey {
        ConfigKey {
            name: self.name,
            scope: ConfigScope::Broker,
            config_type: self.config_type,
            type_note: None,
            default: self.default,
            doc: "",
            read_only: matches!(self.dynamic, ReadOnly),
            sensitive: matches!(self.config_type, Password),
            internal: self.internal,
            kip: None,
            cluster_default: None,
            check: ValueCheck::Parsed,
        }
    }

    /// Kafka's `ConfigDef.parse` of one value of this key, returned in the
    /// form Kafka reports it: trimmed, a boolean in lower case, a number as it
    /// parses, a list joined with bare commas.
    ///
    /// A `CLASS` value is not loaded, because there is no JVM to load it
    /// into: Kafka would answer `Class <name> could not be found.` for a name
    /// its class path lacks, and this accepts the name.
    ///
    /// # Errors
    /// Returns Kafka's `ConfigException` text, which the alter paths answer
    /// with `INVALID_REQUEST`.
    pub(crate) fn canonical(&self, value: &str) -> Result<String, String> {
        let key = self.name;
        let at_least = |parsed: i64| match self.check {
            AtLeast(min) => check_range(key, parsed, Some(min), None),
            _ => Ok(parsed),
        };
        match self.config_type {
            Bool => parse_bool(key, value).map(|parsed| parsed.to_string()),
            Int => at_least(i64::from(parse_int(key, value)?)).map(|parsed| parsed.to_string()),
            Short => at_least(i64::from(parse_short(key, value)?)).map(|parsed| parsed.to_string()),
            Long => at_least(parse_long(key, value)?).map(|parsed| parsed.to_string()),
            Double => parse_double(key, value).map(java_double),
            Str => match self.check {
                OneOf(accepted) => check_one_of(key, value, accepted).map(str::to_owned),
                _ => Ok(java_trim(value).to_owned()),
            },
            Class | Password => Ok(java_trim(value).to_owned()),
            List => check_valid_list(key, value, &[], !matches!(self.check, NonEmptyList))
                .map(|values| values.join(",")),
        }
    }
}

#[cfg(test)]
mod tests;
