//! The checked-in config schema and reference page track `FileConfig`.
//!
//! `docs/config-schema.json` is what `krabka-broker --print-config-schema`
//! prints, and `docs/config-reference.md` is what
//! `aspect generate-config-reference` renders from it. The docs CI job
//! regenerates the page and diffs it, but that job has no Rust toolchain, so
//! the schema itself is compared here: a `FileConfig` change that is not
//! followed by a regeneration fails this suite.

use std::path::PathBuf;

use assert2::assert;
use serde_json::Value;

/// The repository root, under Cargo or under a Bazel test sandbox.
fn repo_root() -> PathBuf {
    if let Ok(dir) = std::env::var("CARGO_MANIFEST_DIR") {
        return PathBuf::from(dir).join("../..");
    }
    let srcdir = std::env::var("TEST_SRCDIR")
        .expect("CARGO_MANIFEST_DIR (cargo) or TEST_SRCDIR (bazel) must be set");
    let workspace =
        std::env::var("TEST_WORKSPACE").expect("TEST_WORKSPACE accompanies TEST_SRCDIR");
    PathBuf::from(srcdir).join(workspace)
}

fn checked_in_schema() -> Value {
    let path = repo_root().join("docs/config-schema.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    serde_json::from_str(&text).expect("docs/config-schema.json is JSON")
}

#[test]
fn checked_in_schema_matches_file_config() {
    let generated = krabka_broker::file_config::config_schema();
    let checked_in = checked_in_schema();
    assert!(
        generated == checked_in,
        "docs/config-schema.json is stale: run `krabka-broker --print-config-schema > \
         docs/config-schema.json` and then `aspect generate-config-reference`"
    );
}

/// Every key the schema knows, as the bare key name a reference row carries.
fn schema_keys(schema: &Value) -> Vec<String> {
    fn walk(root: &Value, node: &Value, out: &mut Vec<String>) {
        let node = match node.get("$ref").and_then(Value::as_str) {
            Some(reference) => {
                let name = reference
                    .strip_prefix("#/$defs/")
                    .expect("schemars emits local $defs refs");
                &root["$defs"][name]
            }
            None => node,
        };
        if let Some(properties) = node.get("properties").and_then(Value::as_object) {
            for (key, field) in properties {
                out.push(key.clone());
                walk(root, field, out);
            }
        }
        for branch_list in ["anyOf", "oneOf"] {
            if let Some(branches) = node.get(branch_list).and_then(Value::as_array) {
                for branch in branches {
                    walk(root, branch, out);
                }
            }
        }
        if let Some(items) = node.get("items") {
            walk(root, items, out);
        }
    }
    let mut keys = Vec::new();
    walk(schema, schema, &mut keys);
    keys.sort();
    keys.dedup();
    keys
}

#[test]
fn reference_page_carries_every_schema_key() {
    let path = repo_root().join("docs/config-reference.md");
    let page = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
    assert!(
        page.contains("<!-- Generated by `aspect generate-config-reference`"),
        "docs/config-reference.md must carry the generated banner"
    );
    let missing: Vec<String> = schema_keys(&checked_in_schema())
        .into_iter()
        .filter(|key| !page.contains(&format!("| `{key}` |")))
        .collect();
    assert!(
        missing.is_empty(),
        "docs/config-reference.md has no row for {missing:?}: run \
         `aspect generate-config-reference`"
    );
}

/// The binary prints the same document the library generates, so the
/// regeneration command in this suite's failure message produces what the
/// test compares against.
#[test]
fn print_config_schema_flag_prints_the_schema() {
    let exe = std::env::var_os("CARGO_BIN_EXE_krabka-broker")
        .expect("cargo and the Bazel target both export CARGO_BIN_EXE_krabka-broker");
    let output = std::process::Command::new(exe)
        .arg("--print-config-schema")
        .output()
        .expect("spawn krabka-broker");
    assert!(
        output.status.success(),
        "krabka-broker --print-config-schema failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let printed: Value =
        serde_json::from_slice(&output.stdout).expect("--print-config-schema prints JSON");
    assert!(printed == krabka_broker::file_config::config_schema());
}

#[test]
fn schema_names_the_top_level_sections() {
    let schema = krabka_broker::file_config::config_schema();
    let properties = schema["properties"]
        .as_object()
        .expect("FileConfig schema has properties");
    for section in [
        "listeners",
        "tls_config",
        "oauthbearer",
        "gssapi",
        "authorization",
        "audit",
        "remote_storage",
        "operator_keys",
        "controller_quorum_voters",
        "runtime",
    ] {
        assert!(
            properties.contains_key(section),
            "FileConfig schema lost the `{section}` key"
        );
    }
}

#[test]
fn unit_bearing_fields_carry_their_format() {
    let schema = krabka_broker::file_config::config_schema();
    let runtime = &schema["$defs"]["RuntimeFileConfig"]["properties"];
    let expected = [
        ("heartbeat_interval", "duration"),
        ("log_segment_bytes", "byte-size"),
        ("leader_imbalance_per_broker", "ratio"),
    ];
    for (key, format) in expected {
        assert!(
            runtime[key]["format"] == format,
            "[runtime] {key} should carry format {format}, got {}",
            runtime[key]
        );
    }
    assert!(schema["properties"]["heartbeat_interval"]["format"] == "duration");
}
