#!/usr/bin/env python3
"""Render docs/config-reference.md from docs/config-schema.json.

The schema is the JSON Schema that `krabka-broker --print-config-schema`
prints for `FileConfig`, the `--config-file` document. Every `///` comment on
a config field is the `description` of that field in the schema, so this
script does not read Rust source: the doc comments are the reference text.

Usage: generate-config-reference.py [OUTPUT]

Without OUTPUT the page is written to docs/config-reference.md. CI renders it
to a temporary file and diffs the two, so a schema change that is not followed
by a regeneration fails the docs job.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "docs" / "config-schema.json"
DEFAULT_OUTPUT = ROOT / "docs" / "config-reference.md"

BANNER = (
    "<!-- Generated by tools/generate-config-reference.py from "
    "docs/config-schema.json; do not edit by hand. -->"
)

HEADER = """# Broker configuration reference

{banner}

`krabka-broker --config-file PATH` reads one TOML document. This page lists
every key that document accepts, with the type, the default, the units, and
the description from the field's doc comment. A key whose default is `broker
default` leaves the broker's built-in value in place when it is absent. The
CLI flag or environment variable for the same setting, when one exists, wins
over the file.

The schema behind this page is [`docs/config-schema.json`](config-schema.json),
which `krabka-broker --print-config-schema` prints. Two annotated examples sit
beside it: [`broker-single-node.toml`](examples/broker-single-node.toml) and
[`broker-three-node-quorum.toml`](examples/broker-three-node-quorum.toml).

A `duration` is a string with a unit suffix, for example `"500ms"`, `"30s"`,
or `"10m"`. A `byte size` is a string with a unit suffix, for example `"1MiB"`
or `"10GB"`. A `ratio` is a string such as `"10%"` or `"0.1"`. A key whose
units column says `milliseconds` or `seconds` is a plain integer in that unit.

"""

# The `format` a `Time`, `ByteSize`, or `Ratio` field carries in the schema,
# and the word the units column uses for it.
FORMAT_UNITS = {
    "duration": "duration",
    "byte-size": "byte size",
    "ratio": "ratio",
}
# Integer keys name their unit in the key itself, Kafka style.
KEY_UNITS = (
    (re.compile(r"_ms$"), "milliseconds"),
    (re.compile(r"_secs$|_seconds$"), "seconds"),
    (re.compile(r"_bytes$"), "bytes"),
)
# An integer key without a unit suffix can still say its unit in its doc
# comment.
DESCRIPTION_UNITS = (
    (re.compile(r"\bmilliseconds\b"), "milliseconds"),
    (re.compile(r"\bseconds\b"), "seconds"),
    (re.compile(r"\bbytes\b"), "bytes"),
    (re.compile(r"\bentries\b"), "entries"),
)

TABLE_HEAD = [
    "| Key | Type | Default | Units | Description |",
    "| :--- | :--- | :--- | :--- | :--- |",
]


def resolve(root, schema):
    """Follow a `$ref` to its `$defs` entry, or return `schema` unchanged."""
    ref = schema.get("$ref")
    if ref is None:
        return schema
    if not ref.startswith("#/$defs/"):
        raise SystemExit(f"unsupported $ref {ref}")
    return root["$defs"][ref[len("#/$defs/"):]]


def effective(root, schema):
    """The non-null branch of an `Option<T>` schema, resolved.

    schemars renders `Option<Struct>` as `anyOf: [{$ref}, {type: null}]` and
    `Option<scalar>` as `type: [scalar, "null"]`. Both collapse to the inner
    schema here so the caller sees one shape. The field's own description and
    default survive the collapse.
    """
    schema = resolve(root, schema)
    branches = schema.get("anyOf")
    if branches is not None:
        inner = [b for b in branches if b.get("type") != "null"]
        if len(inner) == 1:
            merged = dict(resolve(root, inner[0]))
            for key in ("description", "default"):
                if key in schema and key not in merged:
                    merged[key] = schema[key]
            return merged
    return schema


def type_names(schema):
    """The JSON types of `schema`, with `null` removed."""
    kind = schema.get("type", [])
    if isinstance(kind, str):
        kind = [kind]
    return [k for k in kind if k != "null"]


def is_nullable(schema):
    kind = schema.get("type", [])
    if isinstance(kind, list) and "null" in kind:
        return True
    return any(b.get("type") == "null" for b in schema.get("anyOf", []))


def enum_values(schema):
    """The allowed strings of a unit enum, whether `enum` or `oneOf` consts."""
    if "enum" in schema:
        return list(schema["enum"])
    consts = [b.get("const") for b in schema.get("oneOf", [])]
    if consts and all(isinstance(c, str) for c in consts):
        return consts
    return None


def is_table(root, schema):
    """Whether `schema` is a struct: a TOML `[table]` or `[[array of tables]]`."""
    return "properties" in effective(root, schema)


def is_tagged_union(root, schema):
    """A `oneOf` whose branches are structs with a `type` discriminator."""
    branches = effective(root, schema).get("oneOf")
    if not branches:
        return False
    return all("properties" in resolve(root, b) for b in branches)


def type_label(root, schema):
    schema = effective(root, schema)
    if "const" in schema:
        return f"constant `{json.dumps(schema['const'])}`"
    values = enum_values(schema)
    if values is not None:
        return "one of " + ", ".join(f"`{v}`" for v in values)
    kinds = type_names(schema)
    if kinds == ["array"]:
        items = schema.get("items", {})
        if is_table(root, items):
            return "array of tables"
        return f"array of {type_label(root, items)}"
    if kinds == ["object"]:
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"map of string to {type_label(root, extra)}"
        return "table"
    if kinds == ["integer"]:
        fmt = schema.get("format")
        return f"integer ({fmt})" if fmt else "integer"
    if len(kinds) == 1:
        return kinds[0]
    if not kinds:
        return "any"
    return " or ".join(kinds)


def default_label(field, resolved, required):
    """The Default column.

    A field is `required` when its parent's `required` list names it. A
    `default` in the schema is the value serde fills in. A nullable field with
    neither leaves the broker's own default in place.
    """
    if required:
        return "required"
    if "default" in resolved and resolved["default"] is not None:
        return f"`{json.dumps(resolved['default'])}`"
    if is_nullable(field) or "default" in resolved:
        return "broker default"
    if type_names(resolved) == ["array"]:
        return "`[]`"
    return "broker default"


def units_label(key, resolved):
    fmt = resolved.get("format")
    if fmt in FORMAT_UNITS:
        return FORMAT_UNITS[fmt]
    for pattern, unit in KEY_UNITS:
        if pattern.search(key):
            return unit
    if type_names(resolved) == ["integer"]:
        description = resolved.get("description", "")
        for pattern, unit in DESCRIPTION_UNITS:
            if pattern.search(description):
                return unit
    return ""


def cell(text):
    """Flatten a description into one table cell."""
    text = re.sub(r"\n\s*\n", " ", text.strip())
    text = re.sub(r"\s+", " ", text.replace("\n", " "))
    return text.replace("|", "\\|")


def blurb(schema):
    """A description as the lead of a table cell, or nothing."""
    text = cell(schema.get("description", ""))
    return f"{text} " if text else ""


def render_table(root, schema, path, depth, out):
    """Render one struct as a table, then its nested structs as subsections.

    Scalar keys go into the section's table. A key that is itself a struct
    gets a row that points at its own subsection, named by its dotted TOML
    path, so `[remote_storage.s3]` follows `[remote_storage]`.
    """
    resolved = effective(root, schema)
    required = set(resolved.get("required", []))
    nested = []
    rows = []
    for key, field in resolved.get("properties", {}).items():
        child = f"{path}.{key}" if path else key
        target = effective(root, field)
        is_required = key in required
        if is_tagged_union(root, field):
            nested.append((child, field, "union"))
            rows.append(
                f"| `{key}` | table | {default_label(field, target, is_required)} |  | "
                f"{blurb(target)}See the `[{child}]` sections below. |"
            )
            continue
        if is_table(root, field):
            nested.append((child, field, "table"))
            rows.append(
                f"| `{key}` | table | {default_label(field, target, is_required)} |  | "
                f"{blurb(target)}See `[{child}]` below. |"
            )
            continue
        items = target.get("items")
        if items is not None and is_table(root, items):
            nested.append((child, items, "array"))
            rows.append(
                f"| `{key}` | array of tables | {default_label(field, target, is_required)} |  | "
                f"{blurb(target)}See `[[{child}]]` below. |"
            )
            continue
        rows.append(
            f"| `{key}` | {type_label(root, field)} | "
            f"{default_label(field, target, is_required)} | "
            f"{units_label(key, target)} | {cell(target.get('description', ''))} |"
        )
    if rows:
        out.extend(TABLE_HEAD)
        out.extend(rows)
        out.append("")
    heading = "#" * min(depth + 1, 6)
    for child, field, kind in nested:
        if kind == "union":
            for branch in effective(root, field)["oneOf"]:
                branch = resolve(root, branch)
                tag = branch["properties"]["type"]["const"]
                out.append(f'{heading} `[{child}]` with `type = "{tag}"`')
                out.append("")
                if branch.get("description"):
                    out.append(cell(branch["description"]))
                    out.append("")
                render_table(root, branch, child, depth + 1, out)
            continue
        target = effective(root, field)
        if kind == "array":
            out.append(f"{heading} `[[{child}]]`")
        else:
            out.append(f"{heading} `[{child}]`")
        out.append("")
        if target.get("description"):
            out.append(cell(target["description"]))
            out.append("")
        render_table(root, target, child, depth + 1, out)


def render(root):
    out = [HEADER.format(banner=BANNER).rstrip(), "", "## Top-level keys", ""]
    render_table(root, root, "", 2, out)
    return "\n".join(out).rstrip() + "\n"


def main(argv):
    output = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT
    root = json.loads(SCHEMA.read_text())
    output.write_text(render(root))


if __name__ == "__main__":
    main(sys.argv)
