#!/usr/bin/env python3
"""Generate the checked-in Kafka on-disk compatibility evidence matrix."""

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TESTS = ROOT / "crates/log/tests/integration.rs"
LOG_BUILD = ROOT / "crates/log/BUILD.bazel"
IMAGES = ROOT / "bazel/images/BUILD.bazel"
MODULE = ROOT / "MODULE.bazel"
ROWS = (
    (
        "JVM -> krabka",
        "Open and read a JVM-written Kafka log directory",
        "read_jvm_produced_log_dir",
    ),
    (
        "krabka -> JVM",
        "Restart Kafka over a krabka-written log directory and consume it",
        "jvm_consumes_rust_written_log_dir",
    ),
)


def match(pattern: str, text: str, source: Path) -> str:
    found = re.search(pattern, text, re.MULTILINE)
    if not found:
        raise SystemExit(f"missing matrix evidence in {source}: {pattern}")
    return found.group(1)


def render() -> str:
    tests = TESTS.read_text()
    for _, _, test in ROWS:
        match(rf"^async fn ({re.escape(test)})\(\)", tests, TESTS)

    image_key = match(
        r'docker\s*=\s*\{\s*"integration"\s*:\s*\["([^"]+)"\]',
        LOG_BUILD.read_text(),
        LOG_BUILD,
    )
    image = match(
        rf'^\s*"{re.escape(image_key)}"\s*:\s*"([^"]+)"',
        IMAGES.read_text(),
        IMAGES,
    )
    test_image = match(r'^const KAFKA_IMAGE: &str = "([^"]+)";', tests, TESTS)
    test_tag = match(r'^const KAFKA_TAG: &str = "([^"]+)";', tests, TESTS)
    if f"{test_image}:{test_tag}" != image:
        raise SystemExit(
            f"test image {test_image}:{test_tag} does not match Bazel image {image}"
        )
    digest = match(
        rf'^\s*\("{re.escape(image_key)}",\s*"[^"]+",\s*"([^"]+)"\)',
        MODULE.read_text(),
        MODULE,
    )

    rows = "\n".join(
        f"| {direction} | Implemented | {contract} | "
        f"[`crates/log`](../crates/log) | "
        f"[`{test}`](../crates/log/tests/integration.rs) | `{image}@{digest}` |"
        for direction, contract, test in ROWS
    )
    return f"""# Kafka KIP compatibility matrix

<!-- Generated by tools/generate-kip-matrix.py; do not edit by hand. -->

This matrix records the repository's JVM differential evidence for the Kafka
on-disk log contract. The suite covers timestamped record batches (KIP-32),
segment and index discovery, and record key/value recovery in both directions.

| Direction | Status | Contract | Owner | Differential test | Kafka image |
| :--- | :--- | :--- | :--- | :--- | :--- |
{rows}

The Bazel Docker lane supplies the image from a digest-pinned OCI repository.
CI regenerates this page and fails when the test names, lane, image tag, digest,
or checked-in output drift.
"""


output = Path(sys.argv[1]) if len(sys.argv) == 2 else ROOT / "docs/KIP_MATRIX.md"
if len(sys.argv) > 2:
    raise SystemExit(f"usage: {Path(sys.argv[0]).name} [OUTPUT]")
output.write_text(render())
