#!/usr/bin/env python3
"""Generate the checked-in Kafka on-disk compatibility evidence matrix."""

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TESTS = ROOT / "crates/log/tests/integration.rs"
LOG_BUILD = ROOT / "crates/log/BUILD.bazel"
IMAGES = ROOT / "bazel/images/BUILD.bazel"
MODULE = ROOT / "MODULE.bazel"
THROTTLE_AUDIT = ROOT / "crates/broker/src/network/dispatch/throttle_audit.rs"
ROWS = (
    (
        "JVM -> krabka",
        "Open and read a JVM-written Kafka log directory",
        "read_jvm_produced_log_dir",
    ),
    (
        "krabka -> JVM",
        "Restart Kafka over a krabka-written log directory and consume it",
        "jvm_consumes_rust_written_log_dir",
    ),
)


# KIP-219 (throttle-then-respond) responses the broker delays but does not
# echo, because `ThrottleTimeMs` is not the leading field of the response body
# and the dispatch loop reports the delay by patching a leading int32. Each row
# is one entry of `THROTTLE_ECHO_DIVERGENCES` in the audit module below, which
# fails if the broker starts or stops diverging on any advertised version.
THROTTLE_ECHO_ROWS = (
    ("Produce", "0", "1-13", "Sits behind the `Responses` array; the handler charges the bandwidth quota itself and fills the field in before encoding"),
    ("ApiVersions", "18", "1-5", "Sits behind the `ApiKeys` array, at an offset the response header does not fix"),
    ("CreateDelegationToken", "38", "1-3", "Last field, behind the principal strings, the token timestamps and the HMAC"),
    ("RenewDelegationToken", "39", "1-2", "Last field, behind `ErrorCode` and the new expiry timestamp"),
    ("ExpireDelegationToken", "40", "1-2", "Last field, behind `ErrorCode` and the new expiry timestamp"),
    ("DescribeDelegationToken", "41", "1-3", "Last field, behind `ErrorCode` and the variable-length token list"),
    ("OffsetDelete", "47", "0", "Leads with `ErrorCode`; the field is at a fixed offset of 2, but the dispatch loop patches leading fields only"),
)
THROTTLE_AUDIT_TEST = "throttle_echo_divergences_are_the_recorded_ones"


def match(pattern: str, text: str, source: Path) -> str:
    found = re.search(pattern, text, re.MULTILINE)
    if not found:
        raise SystemExit(f"missing matrix evidence in {source}: {pattern}")
    return found.group(1)


def render() -> str:
    tests = TESTS.read_text()
    for _, _, test in ROWS:
        match(rf"^async fn ({re.escape(test)})\(\)", tests, TESTS)

    image_key = match(
        r'docker\s*=\s*\{\s*"integration"\s*:\s*\["([^"]+)"\]',
        LOG_BUILD.read_text(),
        LOG_BUILD,
    )
    image = match(
        rf'^\s*"{re.escape(image_key)}"\s*:\s*"([^"]+)"',
        IMAGES.read_text(),
        IMAGES,
    )
    test_image = match(r'^const KAFKA_IMAGE: &str = "([^"]+)";', tests, TESTS)
    test_tag = match(r'^const KAFKA_TAG: &str = "([^"]+)";', tests, TESTS)
    if f"{test_image}:{test_tag}" != image:
        raise SystemExit(
            f"test image {test_image}:{test_tag} does not match Bazel image {image}"
        )
    digest = match(
        rf'^\s*\("{re.escape(image_key)}",\s*"[^"]+",\s*"([^"]+)"\)',
        MODULE.read_text(),
        MODULE,
    )

    audit = THROTTLE_AUDIT.read_text()
    match(rf"^fn ({re.escape(THROTTLE_AUDIT_TEST)})\(\)", audit, THROTTLE_AUDIT)
    for _, key, versions, _ in THROTTLE_ECHO_ROWS:
        low, _, high = versions.partition("-")
        match(
            rf"^\s+(\({re.escape(key)}, {re.escape(low)}, {re.escape(high or low)}\)),",
            audit,
            THROTTLE_AUDIT,
        )

    throttle_rows = "\n".join(
        f"| {api} | {key} | {versions} | {reason} |"
        for api, key, versions, reason in THROTTLE_ECHO_ROWS
    )

    rows = "\n".join(
        f"| {direction} | Implemented | {contract} | "
        f"[`crates/log`](../crates/log) | "
        f"[`{test}`](../crates/log/tests/integration.rs) | `{image}@{digest}` |"
        for direction, contract, test in ROWS
    )
    return f"""# Kafka KIP compatibility matrix

<!-- Generated by tools/generate-kip-matrix.py; do not edit by hand. -->

This matrix records the repository's JVM differential evidence for the Kafka
on-disk log contract. The suite covers timestamped record batches (KIP-32),
segment and index discovery, and record key/value recovery in both directions.

| Direction | Status | Contract | Owner | Differential test | Kafka image |
| :--- | :--- | :--- | :--- | :--- | :--- |
{rows}

The Bazel Docker lane supplies the image from a digest-pinned OCI repository.
CI regenerates this page and fails when the test names, lane, image tag, digest,
or checked-in output drift.

## KIP-219 throttle-echo divergences

The broker reports a request-quota delay by patching the leading `ThrottleTimeMs`
int32 of an already-encoded response, so it can only echo the delay on responses
whose schema puts that field first. Every other advertised API is audited by
[`throttle_audit`](../crates/broker/src/network/dispatch/throttle_audit.rs),
which encodes each response at each advertised version and compares where
`ThrottleTimeMs` lands against the broker's table.

The APIs below are still throttled -- the connection mute enforces the delay --
but the response reports `throttle_time_ms = 0`, so a client sees latency
instead of a back-off signal. Echoing them needs the typed response rather than
a byte patch.

| API | api_key | Versions | Why the field cannot be patched |
| :--- | :--- | :--- | :--- |
{throttle_rows}
"""


output = Path(sys.argv[1]) if len(sys.argv) == 2 else ROOT / "docs/KIP_MATRIX.md"
if len(sys.argv) > 2:
    raise SystemExit(f"usage: {Path(sys.argv[0]).name} [OUTPUT]")
output.write_text(render())
